# The name of the current part. The name will stand on the sidebar
name: Part 2

# Optional: The description of the part
description: This is a description

# The content of the part.
items:
- name: Welcome
  description: Welcome to the course
  type: video
  source: youtube
  url: ScMzIvxBSi4
- name: Text
  type: text
  text: >
    Here you can write something. Markdown is supported!
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  time: 600
  type: quiz
  questions:
  - title: Question 1 title
    description: Question 1 description
    evaluation: An evaluation
    answers:
    - name: A
    - name: B
    - name: C
      correct: true
    - name: D
      correct: true