# The name of the current part. The name will stand on the sidebar
name: Website erstellung in HTML

# Optional: The description of the part
description: In diesem Kurs lernst du schnell und einfach alles was du für die Webentwicklung benötigst.

# The content of the part.
items:
- name: Part 1: HTML Basics
  description: In diesem Video werden die wichtigsten Grundkenntnisse der Websiteentwicklung erläutert.
  type: video
  source: youtube
  url: https://www.youtube.com/watch?v=S7hsJvqDsS4&list=PLM5uQJ9q3K5UF-zkdht8rZ4kfahClmZAV
- name: Zusammenfassung
  type: text
  text: |
    Der Website einen Titel geben:
    ```html
      <title> HTML Basics </title>
    ```
    type: text
  text: |
    Eine Überschrift erstellen:
    ```html
      <h1> Überschrift [Groß] </h1>
    ```
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  time: 600
  type: quiz
  questions:
  - title: Wie gibst du der Website einen Titel?
    description: Es gibt 3 Auswahlmöglichkeiten, doch nur eine ist richtig.
    evaluation: An evaluation
    answers:
    - name: <titel></titel>
    - name: <title></title>
      correct: true
    - name: <name></name>
