# The name of the current part. The name will stand on the sidebar
name: HTML Basics

# Optional: The description of the part
description: In diesem Kurs lernst du schnell und einfach die Basics die du für die Web-Entwicklung benötigst.

# The content of the part.
items:
- name: HTML Basics
  description: Ein kleines Video zu erläuterung der Basics.
  type: video
  source: youtube
  url: https://www.youtube.com/watch?v=S7hsJvqDsS4&list=PLM5uQJ9q3K5UF-zkdht8rZ4kfahClmZAV
- name: Zusammenfassung
  type: text
  text: |
    Der Website einen Titel geben:
    ```html
      <title> HTML Basics </title>
    ```
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  time: 600
  type: quiz
  questions:
  - title: Wie gibst du der Website einen Titel?
    description: Es gibt 3 Auswahlmöglichkeiten, doch nur eine ist richtig.
    evaluation: An evaluation
    answers:
    - name: <titel></titel>
    - name: <title></title>
    - name: <name></name>
      correct: true
